# Generated by Django 3.1.4 on 2020-12-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='sotrage_capacity',
            new_name='storage_capacity',
        ),
        migrations.AddField(
            model_name='laptop',
            name='malfunction',
            field=models.TextField(default=''),
        ),
    ]
