# Generated by Django 3.1.4 on 2020-12-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201221_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model_type',
            field=models.CharField(choices=[('HP-ProBook', 'HP-ProBook'), ('HP-Compaq', 'HP-Compaq'), ('HP-Elitebook', 'HP-Elitebook'), ('Asus-N46VM', 'Asus-N46VM'), ('Lenovo-Thinkpad', 'Lenovo-Thinkpad')], default='HP-ProBook', max_length=20),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(choices=[('I3', 'I3'), ('I5', 'I5'), ('I7', 'I7')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(choices=[('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_model',
            field=models.CharField(choices=[('Hitachi (HGST)', 'Hitachi (HGST)'), ('WD (Westernd Digital)', 'WD (Westernd Digital)'), ('Seagate', 'Seagate'), ('Toshiba', 'Toshiba'), ('OCZ Vertex', 'OCZ Vertex'), ('Samsung 860 Vevo', 'Samsung 860 Vevo')], default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], default='', max_length=4),
        ),
    ]
